corpus-viewer/viewer-framework/dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^documentation$', views.documentation, name='documentation'),
    url(r'^delete_session$', views.delete_session, name='delete_session'),
]

corpus-viewer/viewer-framework/viewer-framework/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls')),
    url(r'^viewer/', include('viewer.urls')),
    url(r'^example_app/', include('example_app.urls')),
    url(r'^web_page_annotation/',include('web_page_annotation.urls')),
]

corpus-viewer/viewer-framework/viewer/urls.py
from django.urls import path

from . import views

app_name = 'viewer'
urlpatterns = [
    path('<str:id_corpus>', views.index, name='index'),
    path('<str:id_corpus>/<int:id_internal_item>', views.view_item, name='view_item'),
    path('<str:id_corpus>/get_page', views.get_page, name='get_page'),
    path('<str:id_corpus>/tags/export', views.tags_export, name='tags_export'),
    path('<str:id_corpus>/tags', views.tags, name='tags'),
    path('<str:id_corpus>/enter_token', views.add_token, name='add_token'),
    path('<str:id_corpus>/edit', views.edit, name='edit'),

    # API calls
    path('api/add_corpus', views.api_add_corpus, name='api_add_corpus'),
    path('api/refresh_corpora', views.api_refresh_corpora, name='api_refresh_corpora'),
    path('api/delete_corpus', views.api_delete_corpus, name='api_delete_corpus'),
]

corpus-viewer/viewer-framework/viewer/models.py
from django.db import models
# from .views.shared_code import model_custom
# from settings_viewer import DICT_SETTINGS_VIEWER
# import importlib
# module_custom = importlib.import_module(DICT_SETTINGS_VIEWER['app_label']+'.models')
# model_custom = getattr(module_custom, DICT_SETTINGS_VIEWER['model_name'])

class m_Entity(models.Model):
    class Meta:
        unique_together = ('key_corpus', 'id_item')
        
    key_corpus = models.CharField(max_length=200, null=False)
    id_item = models.CharField(max_length=200, db_index=True, null=False)
    id_item_internal = models.BigIntegerField(db_index=True, null=False)

class m_Tag(models.Model):
    class Meta:
        unique_together = ('key_corpus', 'name')
        ordering = ['name']

    key_corpus = models.CharField(max_length=200, null=False)
    name = models.CharField(max_length=100, null=False)
    color = models.CharField(max_length=7, default="#000000")
    # m2m_custom_model = models.ManyToManyField(model_custom, related_name='viewer_tags')
    m2m_entity = models.ManyToManyField(m_Entity, related_name='viewer_tags')

    def __str__(self):
        return '<Tag [%s]>' % (self.name)

corpus-viewer/viewer-framework/viewer/views/add_token.py
from django.shortcuts import render, redirect
from .shared_code import glob_manager_data
import os 

def add_token(request, id_corpus):
    context = {}

    if request.method == 'POST':
        input_secret_token = request.POST.get('secret_token')
        request.session[id_corpus]['viewer__secret_token'] = input_secret_token
        request.session.modified = True
        return redirect('viewer:index', id_corpus=id_corpus)

    context['secret_token_help'] = glob_manager_data.get_setting_for_corpus('secret_token_help', id_corpus)
    return render(request, 'viewer/add_token.html', context)

corpus-viewer/viewer-framework/viewer/views/api.py
from .shared_code import get_current_corpus, glob_manager_data
from django.http import JsonResponse
import json

def api_refresh_corpora(request):
    dict_result = {}
    
    glob_manager_data.check_for_new_corpora()

    dict_result['success'] = True
    return JsonResponse(dict_result)


def api_add_corpus(request):
    dict_result = {}

    print(request.POST)

    glob_manager_data.add_settings_corpus(request.POST['id_corpus'], json.loads(request.POST['settings']))

    dict_result['success'] = True
    return JsonResponse(dict_result)


def api_delete_corpus(request):
    dict_result = {}

    print(request.POST)
    glob_manager_data.delete_corpus(request.POST['id_corpus'], False)
    # glob_manager_data.add_settings_corpus(request.POST['id_corpus'], json.loads(request.POST['settings']))

    dict_result['success'] = True
    return JsonResponse(dict_result)

corpus-viewer/viewer-framework/viewer/views/edit.py
from .shared_code import get_current_corpus, glob_manager_data
from django.http import JsonResponse
from django.shortcuts import render, redirect

def edit(request, id_corpus):
    # with open('int.bin', 'w') as f:
    #     for x in range(0, 20 * 100 000 000):
    #             f.write(1)

    if not glob_manager_data.get_has_access_to_editing(id_corpus, request):
        return redirect('viewer:index', id_corpus=id_corpus) 

    if request.method == 'POST':
        cookie_id = request.COOKIES['csrftoken']

        content = request.POST['content']
        glob_manager_data.set_settings_content_for_corpus(id_corpus, content)
        if glob_manager_data.reload_settings(id_corpus) == None:
                print('ERROR')
        else:
            return redirect('viewer:index', id_corpus)

    context = {}
    context['content_settings'] = glob_manager_data.get_settings_content_for_corpus(id_corpus)
    context['id_corpus'] = id_corpus
    context['name_corpus'] = glob_manager_data.get_setting_for_corpus('name', id_corpus)
    context['mode_navbar'] = 'viewer'
    return render(request, 'viewer/edit.html', context)

corpus-viewer/viewer-framework/viewer/views/get_page.py
from .shared_code import set_sessions, load_data, get_or_create_tag, \
    get_items_by_indices, get_item_by_ids, glob_manager_data, get_current_corpus, get_filters_if_not_empty
import collections
import re
import os
import time
import json
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect
from django.template import Engine, Context
from django.template.loader import get_template
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from viewer.models import m_Tag, m_Entity
import hashlib
import csv
import importlib
from django.core.exceptions import FieldError
from django.db import connection


regex_filter_numbers_negative = re.compile('(?<![>|\.|>=|<=|<|<|0|1|2|3|4|5|6|7|8|9|0])(-[0-9]+\.?[0-9]*)')
regex_filter_numbers_positive = re.compile('(?<![>|\.|>=|<=|<|<|0|1|2|3|4|5|6|7|8|9|0|-])([0-9]+\.?[0-9]*)')
regex_filter_numbers_lt = re.compile('<(-?[0-9]+\.?[0-9]*)')
regex_filter_numbers_lte = re.compile('<=(-?[0-9]+\.?[0-9]*)')
regex_filter_numbers_gt = re.compile('>(-?[0-9]+\.?[0-9]*)')
regex_filter_numbers_gte = re.compile('>=(-?[0-9]+\.?[0-9]*)')

def get_page(request, id_corpus):
##### handle session entries
    start_total = time.perf_counter()

    if not set_sessions(request, id_corpus):
        raise Http404("Corpus does not exist")

    # id_corpus = get_current_corpus(request)

    if glob_manager_data.has_corpus_secret_token(id_corpus):
        try:
            secret_token = request.session[id_corpus]['viewer__secret_token']
        except KeyError:
            secret_token = None
        if not glob_manager_data.is_secret_token_valid(id_corpus, secret_token):
            return redirect('viewer:add_token')    
##### load data and apply filters
    start = time.time()
    if glob_manager_data.get_setting_for_corpus('data_type', id_corpus) == 'database':
        list_ids, info_filter_values = get_filtered_data_database(request)
    else:
        list_ids, info_filter_values = get_filtered_data(request)
    print('get_filtered_data {}'.format(format(time.time() - start, '.3f')))
##### check if has token for editing
    has_access_to_editing = glob_manager_data.get_has_access_to_editing(id_corpus, request)  
##### handle post requests
    if request.method == 'POST':
        response = {}
        obj = json.loads(request.body.decode("utf-8"))
        if obj['task'] == 'add_tag':
            if has_access_to_editing:
                response['data'] = add_tag(obj, list_ids, request)
        elif obj['task'] == 'export_data':
            response = export_data(obj, data, request)
        elif obj['task'] == 'reload_settings':
            # if has_access_to_editing:
            if glob_manager_data.reload_settings(id_corpus) == None:
                response['success'] = False
            else:
                response['success'] = True
        elif obj['task'] == 'reindex_corpus':
            # if has_access_to_editing:
            try:
                glob_manager_data.reindex_corpus(obj['id_corpus'], obj['class_handle_index'])
            except:
                glob_manager_data.reindex_corpus(id_corpus, obj['class_handle_index'])
        elif obj['task'] == 'get_number_of_indexed_items':
            if id_corpus in glob_manager_data.dict_exceptions:
                response['exception_occured'] = True
            else:
                response['exception_occured'] = False

            response['number_of_indexed_items'] = glob_manager_data.get_number_of_indexed_items(obj['id_corpus'])
            response['state_loaded'] = glob_manager_data.get_state_loaded(obj['id_corpus'])
        elif obj['task'] == 'delete_corpus':
            if has_access_to_editing:
                glob_manager_data.delete_corpus(id_corpus, obj['keep_settings_file'])
        elif obj['task'] == 'create_variable_glob_selected_items':
            response['glob_selected_items'] = create_variable_glob_selected_items(id_corpus, list_ids)

        return JsonResponse(response)
##### page the dataset
    start = time.time()
    # list_tags = []
    list_tags = get_tags_filtered_items(list_ids, request)
    print('get_tags_filtered_items {}'.format(format(time.time() - start, '.3f')))

    start = time.time()
    list_ids = sort_by_columns(request, list_ids)
    print('sort_by_columns {}'.format(format(time.time() - start, '.3f')))

    start = time.time()
    # paginator = Paginator(range(0, get_setting('page_size', request=request))
    paginator = Paginator(list_ids, glob_manager_data.get_setting_for_corpus('page_size', id_corpus))

    print(glob_manager_data.dict_corpora[id_corpus]['size'])

    # if get_filters_if_not_empty(request, id_corpus) == None:
    #     paginator.count = glob_manager_data.dict_corpora[id_corpus]['size']

    # paginator = Paginator(data, get_setting('page_size', request=request))
    try:
        page_current = paginator.page(request.session[id_corpus]['viewer__viewer__page'])
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        page_current = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        page_current = paginator.page(paginator.num_pages)
##### add tags to the dataset
    print('paging {}'.format(format(time.time() - start, '.3f')))

    start_loading = time.perf_counter()

    if glob_manager_data.get_setting_for_corpus('data_type', id_corpus) != 'database':
        data = glob_manager_data.get_items(id_corpus, page_current)
    else:
        data = page_current

    print('loading time: '+str(round(float(time.perf_counter() - start_loading) * 1000, 2))+'ms')

    add_tags(data, request)
##### handle post requests
    context = {}
    context['settings'] = glob_manager_data.get_settings_for_corpus(id_corpus)
    context['data'] = data
    context['id_corpus'] = id_corpus
    context['has_access_to_editing'] = has_access_to_editing

    previous_page_number = None
    next_page_number = None
    if page_current.has_previous():
        previous_page_number = page_current.previous_page_number()
    if page_current.has_next():
        next_page_number = page_current.next_page_number()
    template = get_template('viewer/table.html')

    print('TIME: '+str(round(float(time.perf_counter() - start_total) * 1000, 2))+'ms')

    return JsonResponse({'content': template.render(context, request),
            'tags_filtered_items': list_tags,
            'count_pages': page_current.paginator.num_pages,
            'count_entries': page_current.paginator.count,
            'previous_page_number': previous_page_number,
            'next_page_number': next_page_number,
            'info_filter_values': info_filter_values
        })

def create_variable_glob_selected_items(id_corpus, list_ids):
    dict_selected_items = {}
    field_id = glob_manager_data.get_setting_for_corpus('id', id_corpus)

    if glob_manager_data.get_setting_for_corpus('data_type', id_corpus) == 'database':
        for item in list_ids:
            id_item = str(getattr(item, field_id))
            id_item_internal = item.id

            dict_selected_items[id_item+'-'+str(id_item_internal)] = {
                'id_item': id_item,
                'viewer__id_item_internal': id_item_internal
            }
    else:
        field_id_internal = 'viewer__id_item_internal'

        n = 10
        chunks = [list_ids[x:x+n] for x in range(0, len(list_ids), n)]
        for chunk in chunks:
            list_items = glob_manager_data.get_items(id_corpus, chunk)
            for item in list_items:
                id_item = str(item[field_id])
                id_item_internal = item[field_id_internal]
                dict_selected_items[id_item+'-'+str(id_item_internal)] = {
                    'id_item': id_item,
                    'viewer__id_item_internal': id_item_internal
                }

    # for id_ in list_ids:
    #     print(glob_manager_data.get_item(id_corpus, id_))
        # print(id_)
    return dict_selected_items

def function_sort(id_item, id_corpus, field):
    return glob_manager_data.get_item(id_corpus, id_item)[field]

def sort_by_columns(request, list_ids):
    id_corpus = get_current_corpus(request)

    list_sorted_columns = request.session[id_corpus]['viewer__viewer__sorted_columns']

    if glob_manager_data.get_setting_for_corpus('data_type', id_corpus) == 'database':
        for sorted_column in reversed(list_sorted_columns):
            # print(sorted_column)
            # print(list_ids)
            sign = '-' if sorted_column['order'] == 'desc' else ''
            # print(sign+sorted_column['field'])
            list_ids = list_ids.order_by(sign+sorted_column['field'])
    else:
        for sorted_column in reversed(list_sorted_columns):
            is_reversed = False
            if sorted_column['order'] == 'desc':
                is_reversed = True

            list_ids = sorted(list_ids, key=lambda id_item: function_sort(id_item, id_corpus, sorted_column['field']), reverse=is_reversed)
            print(sorted_column)
    return list_ids

def export_data(obj, data, request):
    response = {}

    data_export = []

    if get_setting('data_type', request=request) == 'database':
        raise NotImplementedError("export for database")
    else:
        db_obj_entities = m_Entity.objects.filter(key_corpus=get_current_corpus(request)).prefetch_related('viewer_tags')
        dict_entities = {entity.id_item: entity for entity in db_obj_entities}

        key_tag = obj['key_tag']

        for item in data:
            try:
                item[key_tag] = [{'id': tag.id, 'name': tag.name, 'color': tag.color} for tag in dict_entities[str(item[get_setting('id', request=request)])].viewer_tags.all()]
            except KeyError:
                # if there is no entity entry in the database
                item[key_tag] = []

        data_export = data

    with open('exported_data.ldjson', 'w') as f:
        for line in data_export:

corpus-viewer/viewer-framework/viewer/views/view_item.py
from django.shortcuts import render, redirect
from viewer.views.shared_code import glob_manager_data, get_current_corpus
from viewer.models import m_Tag, m_Entity
import json
import os
from django.conf import settings
import urllib.request

def view_item(request, id_corpus, id_internal_item):
    # id_corpus = get_current_corpus(request)
    context = {}

    if glob_manager_data.has_corpus_secret_token(id_corpus):
        try:
            secret_token = request.session[id_corpus]['viewer__secret_token']
        except KeyError:
            secret_token = None
        if not glob_manager_data.is_secret_token_valid(id_corpus, secret_token):
            return redirect('viewer:add_token', id_corpus=id_corpus)  

    obj_item = glob_manager_data.get_item(id_corpus, int(id_internal_item))
    queryset_tags = m_Tag.objects.filter(m2m_entity__id_item_internal=id_internal_item, key_corpus=id_corpus)
    obj_item['viewer__tags'] = [{'name': tag.name, 'color': tag.color} for tag in queryset_tags]

    source_external = glob_manager_data.get_setting_for_corpus('external_source', id_corpus)

    if source_external != None:
        id_item = obj_item[glob_manager_data.get_setting_for_corpus('id', id_corpus)]
        url = source_external.replace('PLACEHOLDER_ID', str(id_item))
        if not url.startswith('http'):
            url = 'http://' + url
        print(url)

        with urllib.request.urlopen(url) as response:
            html = response.read().decode("utf8")
            context['template'] = html
    else:

        template_html = glob_manager_data.get_setting_for_corpus('template_html', id_corpus)
        if template_html == None:
            return redirect('viewer:index', id_corpus=id_corpus) 
        else:
            context['template'] = template_html

    context['json_item'] = json.dumps(obj_item)
    context['id_corpus'] = id_corpus
    context['name_corpus'] = glob_manager_data.get_setting_for_corpus('name', id_corpus)

    return render(request, 'viewer/view_item.html', context)

corpus-viewer/viewer-framework/viewer/templates/viewer/add_token.html
{% include "viewer/header.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'dashboard/css/formats.css' %}">
<link rel="stylesheet" href="{% static 'viewer/css/formats_dark.css' %}">

<div class="row">
    <div class="col">
        <h1>Enter password</h1>
    </div>
</div>
<div class="row">
    <div class="col">
    {% if secret_token_help %}
        {{ secret_token_help|safe }}
    {% endif %}
    </div>
</div>
<div class="row">
    <div class="col">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="input_secret_token">Password</label>
                <input type="password" class="form-control" name="secret_token" id="input_secret_token">
            </div>
                <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<script src="{% static 'viewer/js/jquery-3.3.1.min.js' %}"></script>
<!-- <script src="{% static 'viewer/js/tether.js' %}"></script> -->
<script src="{% static 'viewer/js/popper.js' %}"></script>
<script src="{% static 'viewer/js/bootstrap.min.js' %}"></script>
<script src="{% static 'viewer/js/helper_functions.js' %}"></script>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'viewer/css/formats.css' %}" /> -->
{% include "viewer/footer.html" %}

corpus-viewer/viewer-framework/viewer/templates/viewer/footer.html
        </div>
		<script type="text/javascript">
		    $(document).on('click', '#input_toggle_dark_mode', function(event) {
		    	event.preventDefault()
		    	event.stopPropagation();
		    	const elem_checkbox = $(this).find('input');
		    	if(elem_checkbox.prop('checked'))
		    	{
		    		elem_checkbox.prop('checked', false);
		            $('body').removeClass('dark');
		    	} else {
		    		elem_checkbox.prop('checked', true);
		            $('body').addClass('dark');
		    	}
		        set_session_entry('dark_mode', elem_checkbox.prop('checked'));
		    });
		</script>
    </body>
</html>

corpus-viewer/viewer-framework/viewer/templates/viewer/header_navbar.html
{% load tags_custom %}
    <input type="hidden" name="id_corpus" value="{{ id_corpus }}">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            {% if mode_navbar == 'viewer' %}
                <a class="navbar-brand" href="{% url 'viewer:index' id_corpus %}">{{ name_corpus }}</a>
            {% elif mode_navbar == 'tags' %}
                <a class="navbar-brand" href="{% url 'viewer:tags' id_corpus %}">Tags for {{ name_corpus }}</a>
            {% elif mode_navbar == 'dashboard' %}
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">Dashboard</a>
            {% elif mode_navbar == 'documentation' %}
                <a class="navbar-brand" href="{% url 'dashboard:documentation' %}">Documentation</a>
            {% endif %}

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <div class="navbar-nav ml-auto">
            {% get_urls_header as list_urls_header %}
            {% for url in list_urls_header %}
                <a class="nav-item nav-link" href="{{ url.link }}">{{ url.name }}</a>
                
            {% endfor %}
            {% if is_dashboard_available %}
                <a class="nav-item nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
                <a class="nav-item nav-link" href="{% url 'dashboard:documentation' %}">Documentation</a>
            {% endif %}
            </div>
            </div>


            <div class="btn-group btn-group-sm ml-3" role="group">
                <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-cog" ></i>
                </button>
                <div class="dropdown-menu" style="right: 0; left: inherit;">
                    <div id="input_toggle_dark_mode" class=" d-flex" style="cursor: pointer; padding: 0.25rem 1.5rem; user-select: none;">
                        <span class="align-self-center mr-3 text-nowrap">Dark mode</span>
                        <label class="switch align-self-center mb-0" title="Toggle dark mode">
                            <input type="checkbox" {% if dark_mode %}checked{% endif %}>
                            <span class="slider round"></span>
                        </label>
                    </div>
                {% if mode_navbar == 'dashboard' %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" id="submit_refresh_corpora" href="#">Refresh corpora <i class="fa fa-refresh"></i> </a>
                {% elif mode_navbar == 'tags' %}
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#modal_export_tags">Export Tags</a>
                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#modal_import_tags">Import Tags</a>
                {% elif mode_navbar == 'viewer' %}
                    {% load tags_custom %}
                    <a class="dropdown-item" href="#" id="share_link">
                        Copy URL 
                        <i class="fa fa-share" aria-hidden="true" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Copied to clipboard!"></i>
                    </a>
                    <textarea id="input_share_link"></textarea>

                    {% get_is_allowed_editing as is_allowed_editing %}
                    {% get_has_secret_token_editing as has_secret_token_editing %}
                    
                    {% if is_allowed_editing %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" id="submit_reload_settings">Reload settings</a>
                        <a class="dropdown-item" href="{% url 'viewer:edit' id_corpus %}">Edit settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal_reindex_corpus">Reindex corpus</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal_delete_corpus">Delete corpus</a>
                    {% elif has_secret_token_editing %}
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal_enter_token_editing">Enable editing</a>
                    {% endif %}
                {% endif %}
                </div>
            </div>
        </div>
    </nav>

corpus-viewer/viewer-framework/viewer/templates/viewer/table.html
{% load tags_custom %}
{% get_has_template_view_item as has_template_view_item %}

<table class="table table-sm table-hover table-striped">
    <thead>
        <tr>
            <th class="column_viewer__item_selection" {% if not "viewer__item_selection"|in_columns_checked:request %}style="display: none"{% endif %}><input id="input_select_all_items" type="checkbox"></th>
            {% for field in settings.displayed_fields %}
                {% if not field == "viewer__item_selection" and not field == "viewer__tags" %}
                {% get_state_sorted field as state_sorted %}

                <th class="column_{{ field }}" data-sortable="sortable" data-state_sorted="{{ state_sorted }}" {% if not field|in_columns_checked:request %}style="display: none"{% endif %}>
                    <span>
                        {{ field|get_display_name:settings }} 
                        {% if state_sorted == 'asc' %}
                            <i class="fa fa-caret-up indicator_sorting" aria-hidden="true"></i>
                        {% elif state_sorted == 'desc' %}
                            <i class="fa fa-caret-down indicator_sorting" aria-hidden="true"></i>
                        {% endif %}
                    </span>
                </th>
                {% endif %}
            {% endfor %}
            <th class="column_viewer__tags" {% if not "viewer__tags"|in_columns_checked:request %}style="display: none"{% endif %}>Tags</th>
            {% if has_template_view_item %}
            <th class="column_viewer__view_item" {% if not "viewer__view_item"|in_columns_checked:request %}style="display: none"{% endif %}>Detail</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for item in data %}
        <tr class="row_viewer__item" data-id_item="{{ item|get:settings.id }}" data-viewer__id_item_internal="{{ item|get:'viewer__id_item_internal' }}">
            <td class="column_viewer__item_selection" {% if not "viewer__item_selection"|in_columns_checked:request %}style="display: none"{% endif %}>
                <input data-id_item="{{item|get:settings.id}}" data-viewer__id_item_internal="{{ item|get:'viewer__id_item_internal' }}" class="input_select_item" type="checkbox">
            </td>
            {% for field in settings.displayed_fields %}
                {% if not field == "viewer__item_selection" and not field == "viewer__tags" %}
                <td class="column_{{ field }} {% if field|get_type_field:settings == 'text' %}viewer__column_type_text{% endif %}" style="{% if not field|in_columns_checked:request %}display: none;{% endif %}">
                {% if field|get_type_field:settings == 'text' %}
                    <table class="fixed_table" data-id_item="{{ item|get:settings.id }}">
                        <tr>
                            <td style="border-top: none" data-content="{{ item|get:field|escape }}">{{ item|get:field|striptags }}</td>
                        </tr>
                    </table>
                {% else %}
                    <span class="text-nowrap">{{ item|get:field }}</span>
                {% endif %}
                </td>
                {% endif %}
            {% endfor %}

            <td class="column_viewer__tags" {% if not "viewer__tags"|in_columns_checked:request %}style="display: none"{% endif %}>
                <div class="wrapper_tags {{ item.viewer_tags|display_as_tag_classes }}"></div>
                {% if has_access_to_editing %}
                    <a class="link_add_tag" data-id_item="{{item|get:settings.id}}" data-viewer__id_item_internal="{{ item|get:'viewer__id_item_internal' }}" href="#"><i class="fa fa-plus" aria-hidden="true"></i></a>
                {% endif %} 
            </td>
               
            {% if has_template_view_item %}
            <td class="column_viewer__view_item" {% if not "viewer__view_item"|in_columns_checked:request %}style="display: none"{% endif %}>
                <a href="{% url 'viewer:view_item' id_corpus item|get:'viewer__id_item_internal'  %}">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </a>
            </td>
            {% endif %}
        </tr>
        <tr style="display: none;"></tr>
        <tr style="display: none;" class="tr_container_text" data-id_item="{{ item|get:settings.id }}">
            <td class="p-3" colspan="{{ settings.displayed_fields|length|add:2 }}">
                <div class="p-1"></div>
            </td>
        </tr>
        <tr style="display: none;"></tr>
        <tr style="display: none;"></tr>
    {% endfor %}
    </tbody>
</table>